#!/usr/bin/env python
""" Attachment helper tool for openBIS registration """

from __future__ import print_function

import click
import attachi.attachi

@click.command()
@click.argument(
    'project_id',
    required = True,
    metavar = 'PROJECTID'
)
@click.argument(
    'file_path',
    required = True,
    metavar = 'FILE'
)
@click.argument(
    'comment',
    required = True,
    metavar='COMMENT'
)
@click.option(
    '-t', '--atype',
    help = 'Type of attachment: Information or Results (default)',
    metavar='TYPE',
    default="Results"
)
@click.option(
    '-u', '--user',
    help='Username shown in openbis as uploader',
    metavar='ID',
    default=""
)
@click.option(
    '-o', '--outdir',
    metavar='PATH',
    help='Output folder path',
    default=""
)
@click.version_option(attachi.__version__)
def run(project_id, file_path, comment, atype, user, outdir):
    """ Attachi - A helper tool that prepares attachments for openBIS registration"""

    app = attachi.attachi.Attachi(project_id, file_path, comment, atype, user, outdir)
    app.run()

if __name__ == '__main__':
    run()
