#!/usr/bin/env python
""" Attachment helper tool for openBIS registration """

from __future__ import print_function

import click

from attachi.attachi import Attachi

@click.command()
@click.argument(
    'project_id',
    required = True,
    metavar = 'PROJECTID'
)
@click.argument(
    'file_path',
    required = True,
    metavar = 'FILE'
)
@click.argument(
    'comment',
    required = True,
    metavar = 'COMMENT'
)
@click.option(
    '-u', '--user',
    help = 'Username shown in openbis as uploader',
    metavar = 'ID'
)
@click.option(
    '-o', '--outdir',
    metavar = 'PATH',
    help = 'Output folder path'
)
def run(project_id, file_path, comment, user, outdir):
    """ Attachi - A helper tool that prepares attachments for openBIS registration"""
    attachi = Attachi(project_id, file_path, comment, user, outdir)
    attachi.run()

if __name__ == '__main__':
    run()
